### ISSUE TITLE
Missing BN variable

### ISSUE THREAD

**Issue by lfxuan** [carrenD/Medical-Cross-Modality-Domain-Adaptation#10]
Hi ! In the training process, if restore = True, the code will report an error that there are no two variables of BN. Is it necessary to save these two variables during the process of saving the model, or only the last model with the missing BN variable? ( TF1.9.0)

**Comment by 18801109112** [comment]
Hello?  Have you solve this problem? Can you tell me how to solve it? THX!!!!
