### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by lfxuan** [carrenD/Medical-Cross-Modality-Domain-Adaptation#11]
Hi! I am very interested in your work. The model has been trained, but the test code is lacking. Can you upload it to the project? Before, in an answer, you suggested to use evaluate.py of the sifa project, but the training model is different, and the test will prompt the lack of parameters. Looking forward to your reply！

**Comment by cheng-01037** [comment]
Hi lfxuan,
Could you please specify it or directly modify the code accordingly? There seems to be no issues with `evaluate.py` in SIFA.

**Comment by Halleyawoo** [comment]
@lfxuan Hello, how did you implement the test part?
