### ISSUE TITLE
The Preprocess Data Issue

### ISSUE THREAD

**Issue by chenqi1997** [carrenD/Medical-Cross-Modality-Domain-Adaptation#12]
Dear author, I'm trying to train your code on my MRI dataset but I encountered some problems when preprocessing the training data. Would you please kindly share the preprocessing script fit for training the network?Thanks a lot!!!

**Comment by cheng-01037** [comment]
Hi.

Thanks for your interest.

For each 3D volume, we first crop the roi out centered at the heart. The ROI can be found by averageing ground truth label coordinates. The cropped ROIs have a shape of 256 x 256 on coronal plane.

Then, to deal with low contrast and large varieties in intensity levels in MRI and CT in the original dataset (especially for MRI), we cut off top 2% of intensity histogram for each cropped MRI and CT (in 3D). **NOTE: this histogram cut is very beneficial for MRI**

You can also try contrast-limited histogram equalization which might also helps segmentation according to peer literatures.

Then for each 3D image, we **subtract the mean of the entire 3D scan and divide by its standard deviation**.

At last, 3D data augmentation is performed (mainly, affine), and 2D coronal slices with shape 256 x 256 x 3 are sampled and written into 2D tfrecords files.

Hoping that helps.

**Comment by chenqi1997** [comment]
Thanks a lot for your reply！！！



发自我的iPhone


------------------ Original ------------------

**Comment by Halleyawoo** [comment]
Hello!
I met this error:
tensorflow.python.framework.errors_impl.NotFoundError: Key /media/nomachine/project/Medical-Cross-Modality-Domain-Adaptation/listsBatchNorm/beta not found in checkpoint
What is going on, the version is the same as the author？
