### ISSUE TITLE
Out of range: RandomShuffleQueue '_4_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by MinaJf** [carrenD/Medical-Cross-Modality-Domain-Adaptation#13]

**Comment by Halleyawoo** [comment]
Hi, I also encountered the same problem, have you solved it

**Comment by MinaJf** [comment]
Yes, you need to check the list of data and the data folder. They should be totally the same, in terms of names and number of files.

> Hi, I also encountered the same problem, have you solved it

**Comment by Halleyawoo** [comment]
> Yes, you need to check the list of data and the data folder. They should be totally the same, in terms of names and number of files.
> 
> > Hi, I also encountered the same problem, have you solved it

Thx!

**Comment by yingning** [comment]
@MinaJf @carrenD @cheng-01037 @co1037 @Halleyawoo ,Hello ,I also encountered the same problem and I checked the list and data folder.They should be totally the same. Any suggestions to solve the problem？
