### ISSUE TITLE
OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by ljc1231** [carrenD/Medical-Cross-Modality-Domain-Adaptation#15]
OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)
first, thanks for your code, and i have this problem, i don't know why the data didn't read. 
i download the dataset, and i have change the address (in ct_train_list) into absolute address(like /home/lijiachen/下载/Medical-Cross-Modality-Domain-Adaptation-master/lists/mr_train_tfs/mr_train_slice0.tfrecords), but it didn't work.
i also try change batchsize, capacity, num_threads, but it didn't work.
can you help me to solve this problem? it confused me many days,  please. thx

**Comment by cheng-01037** [comment]
Obviously training image files are not correctly loaded. Consider avoiding Chinese characters in filename.

**Comment by ljc1231** [comment]
sorry . i have correct my image_dir, but it also showed the same problem. i want to ask, whether i should put the dataset (mr_train_tfs and mr_val_tfs ) in list. and if i should change any code or do something?

**Comment by cheng-01037** [comment]
the list is essentially a list of paths to individual `.tfrecords` files. It tells tensorflow which file to read as training samples.

**Comment by Halleyawoo** [comment]
> OutOfRangeError：RandomShuffleQueue'_1_shuffle_batch / random_shuffle_queue'已关闭且元素不足（要求1，当前大小为0），
> 首先，感谢您的代码，我有这个问题，我不知道为什么不读取数据。
> 我下载了数据集，并将地址（在ct_train_list中）更改为绝对地址（例如/ home / lijiachen /下载/Medical-Cross-Modality-Domain-Adaptation-master/lists/mr_train_tfs/mr_train_slice0.tfrecords），但是没用。
> 我也尝试更改batchsize，容量，num_threads，但是没有用。
> 您能帮我解决这个问题吗？请让我困惑很多天。谢谢

Hi, I also encountered the same problem, have you solved it

**Comment by Halleyawoo** [comment]
> OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)
> first, thanks for your code, and i have this problem, i don't know why the data didn't read.
> i download the dataset, and i have change the address (in ct_train_list) into absolute address(like /home/lijiachen/下载/Medical-Cross-Modality-Domain-Adaptation-master/lists/mr_train_tfs/mr_train_slice0.tfrecords), but it didn't work.
> i also try change batchsize, capacity, num_threads, but it didn't work.
> can you help me to solve this problem? it confused me many days, please. thx
I also encountered the same problem, have you solved it

**Comment by 18801109112** [comment]
hi, I also met the same problem. Have you solved your problem？
THX
