### ISSUE TITLE
Problem with test code

### ISSUE THREAD

**Issue by Halleyawoo** [carrenD/Medical-Cross-Modality-Domain-Adaptation#19]
Dear author！
Thanks for your work!
Your project does not include the json file in the evaluate.py file: 
(line 231) main(config_filename='./config_param.json'),
and SIFA is a different network model. How can evaluate.py files be used as test files for this project?
Looking forward to your answer.

**Comment by zzs95** [comment]
> Dear author！ Thanks for your work! Your project does not include the json file in the evaluate.py file: (line 231) main(config_filename='./config_param.json'), and SIFA is a different network model. How can evaluate.py files be used as test files for this project? Looking forward to your answer.

Hi! @Halleyawoo Did you implement the test code? Can you tell me something?

**Comment by Halleyawoo** [comment]
> > Dear author！ Thanks for your work! Your project does not include the json file in the evaluate.py file: (line 231) main(config_filename='./config_param.json'), and SIFA is a different network model. How can evaluate.py files be used as test files for this project? Looking forward to your answer.
> 
> Hi! @Halleyawoo Did you implement the test code? Can you tell me something?

I ran the SIFA test code directly. I'm not using this code anymore.  SIFA is more like an updated version of this paper, you can look at SIFA directly.

**Comment by zzs95** [comment]
> 



> > > Dear author！ Thanks for your work! Your project does not include the json file in the evaluate.py file: (line 231) main(config_filename='./config_param.json'), and SIFA is a different network model. How can evaluate.py files be used as test files for this project? Looking forward to your answer.
> > 
> > 
> > Hi! @Halleyawoo Did you implement the test code? Can you tell me something?
> 
> I ran the SIFA test code directly. I'm not using this code anymore. SIFA is more like an updated version of this paper, you can look at SIFA directly.

Thank you for your reply. I rewrote this test code with the `test_model` in `adversarial.py`, this seems more reasonable, instead of using the SIFA test code for PnP-Adanet.
