### ISSUE TITLE
Code for making the tfrecords ?

### ISSUE THREAD

**Issue by mathilde-b** [carrenD/Medical-Cross-Modality-Domain-Adaptation#22]
Hello authors and thank you for your work !
I am using my own augmentation on the whs data, but I'm not able to  write to tfrecords as you specify below : 

"For the ease of training, after data augmentation, training samples are expected to be written into tfrecord with the following format:
feature = {
            # image size, dimensions of 3 consecutive slices
            'dsize_dim0': tf.FixedLenFeature([], tf.int64), # 256
            'dsize_dim1': tf.FixedLenFeature([], tf.int64), # 256
            'dsize_dim2': tf.FixedLenFeature([], tf.int64), # 3
            # label size, dimension of the middle slice
            'lsize_dim0': tf.FixedLenFeature([], tf.int64), # 256
            'lsize_dim1': tf.FixedLenFeature([], tf.int64), # 256
            'lsize_dim2': tf.FixedLenFeature([], tf.int64), # 1
            # image slices of size [256, 256, 3]
            'data_vol': tf.FixedLenFeature([], tf.string),
            # label slice of size [256, 256, 1]
            'label_vol': tf.FixedLenFeature([], tf.string)}"

I followed this tutorial here:
https://gist.github.com/CihanSoylu/02117f2d77136baf41ddb46789d8a331#file-tfrecords-and-tf-train-example-ipynb

basically my script does everything above and serializes the slices like this:

def serialize_example(image, label):
       'dsize_dim0': _int64_feature(256),
        'dsize_dim1': _int64_feature(256),
        'dsize_dim2': _int64_feature(3),
        'lsize_dim0': _int64_feature(256),
        'lsize_dim1': _int64_feature(256),
        'lsize_dim2': _int64_feature(1),
        'data_vol': _bytes_feature(image),
        'label_vol': _bytes_feature(label)
    }
    example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
    return example_proto.SerializeToString()

I save to a new folder. It appears to have worked and that all my augmented slices have been saved in the above tfrecords. I also did the new list mr_train_list_augmented with the path just like yours. But then your code train_segmenter cannot read the tfrecords.

The error is 
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 0)

Do you have a code available to make the tfrecords from nii or from tensors ?

Thanks !
Mathilde

**Comment by kaka0910** [comment]
Hello, do you address this problem? Appreciate for your solution.

**Comment by 18801109112** [comment]
hi, I also met the same problem. Have you solved your problem
THX

**Comment by yingning** [comment]
@kaka0910 @mathilde-b @18801109112 @carrenD @cheng-01037 ，I also met the same problem.Do you address this problem? Appreciate for your solution.

**Comment by carrenD** [comment]
Thanks for the comment. Here is the code to get tfrecords:
https://github.com/cchen-cc/SIFA/blob/master/utils/gettfrecords.py

**Comment by yingning** [comment]
@carrenD  To use your code for my OCT images domain adaptation,I followed  your gettfrecords.py  and used it to generate the tfrecords of my 2D OCT images.  but i still get the problem when I run the train_segmentations.The issue puzzled me a long time .Any help will be appreciated.

**Comment by yingning** [comment]
@carrenD  To use your code for my OCT images domain adaptation,I followed  your gettfrecords.py  and used it to generate the tfrecords of my 2D OCT images.  but i still get the problem when I run the train_segmentations.The issue puzzled me a long time .Any help will be appreciated.

**Comment by cheng-01037** [comment]
@yingning Hi. In short, the queue reads a list path of image slices in the format of `tfrecords` from <ct/mr>_<train/val>_lists. This error usually happens when the file paths for such tfrecords are incorrect (e.g. absolute path vs relative path issue). One way to debug it is to pull that part out and see if the queue functions normally and if the file paths can be read by the queue. Hoping that helps.

**Comment by cchen-cc** [comment]
@yingning Hi, such kind of error usually happens when data cannot be correctly read. There can be various causes for why data are not read correctly and usually careful debugging is needed.
You could check the following things:
- whether the data paths are correct
- whether the data written into the tfrecords are with correct shape and type
- whether the data reading is with correct shape and type

**Comment by yyNoBug** [comment]
> @carrenD To use your code for my OCT images domain adaptation,I followed your gettfrecords.py and used it to generate the tfrecords of my 2D OCT images. but i still get the problem when I run the train_segmentations.The issue puzzled me a long time .Any help will be appreciated.

I also met the same problem. It puzzled me a long time. Have you solved your problem? Thanks

**Comment by yyNoBug** [comment]
> Thanks for the comment. Here is the code to get tfrecords: https://github.com/cchen-cc/SIFA/blob/master/utils/gettfrecords.py

Are you sure your code generates tfrecord files correctly? Running with the example tfrecord data you give produces the same bug (RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements). It seems that the tfrecord file generated by the code is corrupted.

**Comment by yyNoBug** [comment]
> Thanks for the comment. Here is the code to get tfrecords: https://github.com/cchen-cc/SIFA/blob/master/utils/gettfrecords.py

Are you sure the code generating tfrecord is correct? I used your code to generate tfrecords with the example .npz file, but it corrupted and produces the same bug (RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements). However, if I run with the example tfrecord file, it works properly. What might be the problem?

**Comment by cheng-01037** [comment]
@yyNoBug The data loader (goes back to many years ago) fetches tfrecords files according to the file paths written in `\list\ct_<train/val>_list`. You may want to rewrite file paths of your newly generated tfrecords into these lists and see if the data loader can read them correctly.

**Comment by yyNoBug** [comment]
@cheng-01037 Sorry for bothering, but I have really set the correct path. I am sure that the tfrecords I have generated are corrupted (even when using the example .npz file), but I cannot figure out the reason.

**Comment by cheng-01037** [comment]
@yyNoBug You can also try 1. checking if the format of tfrecords here are the same as that described in SIFA; 2. directly read them into your training script without bothering with the coordinator and queuing 3. save and read them using a different format like png or pickle. The data loader at that time is obviously not as intuitive as those in pytorch today ...
