### ISSUE TITLE
binary classification error

### ISSUE THREAD

**Issue by 7LFB** [carrenD/Medical-Cross-Modality-Domain-Adaptation#3]
1. how to do if I only have 2 classes to classify? In adversarial.py, when defing the classifier, it need to concatenate some features into 32 channels, but it can only get 26 channels  for binary classification task. (333-338 rows in original code)
2. the code will corrupt with the error "At least two variables have the same name: adapt_1/adapt_1_1/beta"

thanks!

**Comment by carrenD** [comment]
1. The channels numbers are hard-coded. You can either replicate other channels to full-fill the 32 channels, or change the obtained channel number into 26 for your case.
2. I think it is a small bug with naming of the BN layers...have you resolved this?

**Comment by Cheng-XJTU** [comment]
For issue 2 could you please try Tensorflow 1.4.0 (where the code is written on)? Thanks. It seems that Tensorflow changed their variable naming mechanism after Tensorflow 1.5.0.

**Comment by 7LFB** [comment]
@carrenD @Cheng-XJTU  Thanks, it works on 1.4 version.
Another question, it is time consuming during 'train-gan' phase, about 42s X 200 steps X 600 epochs =58 days according to the default parameter settings. Any suggestions to reduce the time cost?
(BTW, the phase 'warming-up' should be 'pre-train', right?)

**Comment by carrenD** [comment]
You can safely reduce the number of epochs, not necessarily wait until 600. Normally, the train-gan takes upto 2 days.
Yes, warming-up means you pre-train the adaptor layers

**Comment by 7LFB** [comment]
@carrenD Thanks a lot!
