### ISSUE TITLE
the version of pymedimage?

### ISSUE THREAD

**Issue by hucanpei** [carrenD/Medical-Cross-Modality-Domain-Adaptation#4]
Can you provide the version of pymedimage?
I cannot find pymedimage.visualize in PyMedImage https://github.com/ryanneph/PyMedImage.git
function like nio.read_nii_object, nio.write_nii, viz.triple_viewer cannot be found.

**Comment by carrenD** [comment]
I have uploaded the folder of pymedimage in the repo. Then, the nio can be used.
