### ISSUE TITLE
ValueError: At least two variables have the same name: BatchNorm/beta

### ISSUE THREAD

**Issue by sunycl** [carrenD/Medical-Cross-Modality-Domain-Adaptation#8]
when  running this code，I met some problems：
File "Medical-Cross-Modality-Domain-Adaptation-master/source_segmenter.py", line 282, in r
estore
    saver = tf.train.Saver(tf.contrib.framework.get_variables() + tf.get_collection_ref("internal_batchnorm_variables") )
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 482, in _build_internal
    names_to_saveables)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 335, in valida
te_and_slice_inputs
    names_to_saveables = op_list_to_dict(names_to_saveables)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 292, in op_list_to_dict
    name)
ValueError: At least two variables have the same name: BatchNorm/beta

I try to change the tensorFlow version to 1.14, but It didn't work. So what should I do to solve this problems? Thanks very much!

**Comment by mathilde-b** [comment]
Hello, when i run source_segmenter.py, i have the same issue : At least two variables have the same name: BatchNorm/beta. What should I do ? thanks !

**Comment by Halleyawoo** [comment]
Hello!
I met this error:
tensorflow.python.framework.errors_impl.NotFoundError: Key /media/nomachine/project/Medical-Cross-Modality-Domain-Adaptation/listsBatchNorm/beta not found in checkpoint
What is going on, the version is the same as the author？

**Comment by ljc1231** [comment]
> Hello, when i run source_segmenter.py, i have the same issue : At least two variables have the same name: BatchNorm/beta. What should I do ? thanks !

have you solved this probelem?

**Comment by Halleyawoo** [comment]
@ljc1231 I double-checked the path of the file and solved it. I don't know if it helps you.

**Comment by ljc1231** [comment]
> @ljc1231 I double-checked the path of the file and solved it. I don't know if it helps you.

this problem is the ckpt path problem? are you Chinese? Can I email you or add a wechat to communicate?

**Comment by Halleyawoo** [comment]
@ljc1231 就是作者给的lists文件夹里面有读取这些参数的文件，你注意检查一下读取他们的路径对不对，代码应该没问题，这里跟ckpt应该也没关系

**Comment by Halleyawoo** [comment]
@ljc1231 不太好透露微信在这里，公开平台，不好意思啊

**Comment by ljc1231** [comment]
> @ljc1231 不太好透露微信在这里，公开平台，不好意思啊
我可以给你一个qq吗？我这代码上有些问题也想问下，2451810768（如果可以的话超感谢！

**Comment by Halleyawoo** [comment]
@ljc1231 好的 其实我有点不太懂这个代码的逻辑关系 那一块交流一下吧

**Comment by mathilde-b** [comment]
No I haven't :/

**Comment by 18801109112** [comment]
@Halleyawoo 能帮我解释下这个问题吗 想和您交流交流 困扰我好几天了！如果合适的话能加下我的qq吗：838147522
万分万分感谢！！

**Comment by cheng-01037** [comment]
In short, this is a legacy of a really old version tensorflow. Firstly you want to make sure if you are using tensorfllow 1.4 . A higher version might lead to this problem.
The lists of variables are used to let tensorflow know which variables to load when loading a base model to adversarial framework. You can also check that part and see if it is handled properly.
