### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by chinacui** [carrenD/Medical-Cross-Modality-Domain-Adaptation#9]
Hi, thanks for the impressive work. 

The readme said the evaluation code will be released in the future. Then, may I ask whether you can release the code recently?

BTW, TensorFlow 1.6 and CUDA 10.0 can run the code successfully.

Thanks.

**Comment by carrenD** [comment]
Our evaluation code is released with our SIFA repo, can be found here: https://github.com/cchen-cc/SIFA/blob/master/evaluate.py

Thanks a lot for confirmation of success execution with higher versions!

**Comment by lfxuan** [comment]
@chinacui Did you solve the testing problem? Can you share your evaluation code? thank you very much!

**Comment by chinacui** [comment]
@carrenD Thanks for your information. Have implement successfully.
@lfxuan You can directly use the evaluation code of SIFA GitHub.

**Comment by lfxuan** [comment]
Thank you for your answer! But when I try to use Sifa's evaluation code directly, it will prompt that the corresponding parameter cannot be found. Do you write the code for the test part yourself, and then use the code evaluated by the dice and assd of the sifa project?

**Comment by Halleyawoo** [comment]
@lfxuan @chinacui How can I directly use the evaluate.py code, the two network models are different?
